//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaltCommerce.Mobile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaltCommerce.Mobile.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Addresses.
        /// </summary>
        public static string AddressList_Title {
            get {
                return ResourceManager.GetString("AddressList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string AddressTabbedPage_Title {
            get {
                return ResourceManager.GetString("AddressTabbedPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        public static string AskLogOut {
            get {
                return ResourceManager.GetString("AskLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string categoryAll {
            get {
                return ResourceManager.GetString("categoryAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Created Successfully!.
        /// </summary>
        public static string CreateAddressMsg {
            get {
                return ResourceManager.GetString("CreateAddressMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Cart.
        /// </summary>
        public static string DpAddToCart {
            get {
                return ResourceManager.GetString("DpAddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy throut Whatsapp.
        /// </summary>
        public static string DpAskWhatsapp {
            get {
                return ResourceManager.GetString("DpAskWhatsapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string DpCategory {
            get {
                return ResourceManager.GetString("DpCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DpDescription {
            get {
                return ResourceManager.GetString("DpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DpName {
            get {
                return ResourceManager.GetString("DpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string DpPrice {
            get {
                return ResourceManager.GetString("DpPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quatity.
        /// </summary>
        public static string DpQuatity {
            get {
                return ResourceManager.GetString("DpQuatity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifications.
        /// </summary>
        public static string DpSpecifications {
            get {
                return ResourceManager.GetString("DpSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the internet please try again later..
        /// </summary>
        public static string ErrorConnection {
            get {
                return ResourceManager.GetString("ErrorConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Binary.
        /// </summary>
        public static string Gender_NonBinary {
            get {
                return ResourceManager.GetString("Gender_NonBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string InfoMessage {
            get {
                return ResourceManager.GetString("InfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string MenuOptAddresses {
            get {
                return ResourceManager.GetString("MenuOptAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string MenuOptLogOut {
            get {
                return ResourceManager.GetString("MenuOptLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string MenuOptOrders {
            get {
                return ResourceManager.GetString("MenuOptOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Products.
        /// </summary>
        public static string MenuOptProducts {
            get {
                return ResourceManager.GetString("MenuOptProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string MenuOptProfile {
            get {
                return ResourceManager.GetString("MenuOptProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string Method_Delivery {
            get {
                return ResourceManager.GetString("Method_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up.
        /// </summary>
        public static string Method_Pickup {
            get {
                return ResourceManager.GetString("Method_Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have an account to add items to the shopping car!.
        /// </summary>
        public static string MustAccount {
            get {
                return ResourceManager.GetString("MustAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must complete the fields in order to process the request..
        /// </summary>
        public static string MustFillFields {
            get {
                return ResourceManager.GetString("MustFillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Log In For see your profile!.
        /// </summary>
        public static string MustLogIn {
            get {
                return ResourceManager.GetString("MustLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items to display.
        /// </summary>
        public static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Gender.
        /// </summary>
        public static string Option_GenderType {
            get {
                return ResourceManager.GetString("Option_GenderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Personal Id Type.
        /// </summary>
        public static string Option_IdType {
            get {
                return ResourceManager.GetString("Option_IdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to Buy.
        /// </summary>
        public static string PayButtontxt {
            get {
                return ResourceManager.GetString("PayButtontxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string PayM_Cash {
            get {
                return ResourceManager.GetString("PayM_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Transfer.
        /// </summary>
        public static string PayM_Transfer {
            get {
                return ResourceManager.GetString("PayM_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Name.
        /// </summary>
        public static string PhAddressName {
            get {
                return ResourceManager.GetString("PhAddressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Phone.
        /// </summary>
        public static string PhCellPhone {
            get {
                return ResourceManager.GetString("PhCellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string PhCity {
            get {
                return ResourceManager.GetString("PhCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string PhConfirmPassword {
            get {
                return ResourceManager.GetString("PhConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string PhEmail {
            get {
                return ResourceManager.GetString("PhEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string PhFirstName {
            get {
                return ResourceManager.GetString("PhFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House/Building/Apt.
        /// </summary>
        public static string PhHouseNumber {
            get {
                return ResourceManager.GetString("PhHouseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indications.
        /// </summary>
        public static string PhIndication {
            get {
                return ResourceManager.GetString("PhIndication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string PhLastName {
            get {
                return ResourceManager.GetString("PhLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NickName.
        /// </summary>
        public static string PhNickName {
            get {
                return ResourceManager.GetString("PhNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PhPassword {
            get {
                return ResourceManager.GetString("PhPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Id.
        /// </summary>
        public static string PhPersonalId {
            get {
                return ResourceManager.GetString("PhPersonalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string PhProvince {
            get {
                return ResourceManager.GetString("PhProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you looking for?.
        /// </summary>
        public static string PhSearch {
            get {
                return ResourceManager.GetString("PhSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string PhSector {
            get {
                return ResourceManager.GetString("PhSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string PhStreet {
            get {
                return ResourceManager.GetString("PhStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string PhTelephone {
            get {
                return ResourceManager.GetString("PhTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you like to pay the order?.
        /// </summary>
        public static string QPayOrder {
            get {
                return ResourceManager.GetString("QPayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you like to receive the order?.
        /// </summary>
        public static string QReciveOrder {
            get {
                return ResourceManager.GetString("QReciveOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save With Current Location.
        /// </summary>
        public static string SaveCurrentLocationLbl {
            get {
                return ResourceManager.GetString("SaveCurrentLocationLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Address.
        /// </summary>
        public static string tBtnAddNewAddress {
            get {
                return ResourceManager.GetString("tBtnAddNewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the Server please try again later..
        /// </summary>
        public static string TimeOutMessage {
            get {
                return ResourceManager.GetString("TimeOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Summary.
        /// </summary>
        public static string TSummaryOrder {
            get {
                return ResourceManager.GetString("TSummaryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string TtLogin {
            get {
                return ResourceManager.GetString("TtLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string TtRegisUser {
            get {
                return ResourceManager.GetString("TtRegisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Updated Successfully!.
        /// </summary>
        public static string UpdateAddressMsg {
            get {
                return ResourceManager.GetString("UpdateAddressMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string UserAddresses_Title {
            get {
                return ResourceManager.GetString("UserAddresses_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was created successfully !.
        /// </summary>
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string UserProfile_Title {
            get {
                return ResourceManager.GetString("UserProfile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Day.
        /// </summary>
        public static string wBirthDay {
            get {
                return ResourceManager.GetString("wBirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string wSave {
            get {
                return ResourceManager.GetString("wSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Address.
        /// </summary>
        public static string wSaveLocation {
            get {
                return ResourceManager.GetString("wSaveLocation", resourceCulture);
            }
        }
    }
}
